### PR TITLE
Improve ClickHouse: add stand-alone parameters support

### PR DESCRIPTION
**Pull request by Felixoid**
After recent refactoring, it's possible to simplify `cmd` generation with proper processing of stand-alone arguments like `--secure`, `--multiline`, `--multiquery` and so on.

This PR implements the processing for URL parameters w/o values.

### CODE REVIEW

**Comment by tpope** [comment]
This `?param` syntax is nonstandard and kind of weird, which is why I left it undocumented. I think supporting `?arbitrary-flag` is a reasonable behavior, but for known flags, `?secure=true` should remain the official, documented behavior.

Have a look at da00a957ac5d151896d0f9d0abcecf9e50c6037e and see if that looks reasonable to you. I'm also switching to `--param=value` syntax because `--unknown-flag=true` should fail in a less confusing way than `--unknown-flag true`.

**Comment by Felixoid** [comment]
> I'm also switching to `--param=value` syntax because `--unknown-flag=true` should fail in a less confusing way than `--unknown-flag true`.

Yes, `=` for each parameter with argument looks very reasonable!

> This `?param` syntax is nonstandard and kind of weird, which is why I left it undocumented. I think supporting `?arbitrary-flag` is a reasonable behavior, but for known flags, `?secure=true` should remain the official, documented behavior.

Hmm, it looks inconsistent to me. Lately, `clickhouse-client` interface may change in any way, and have arguments that behave differently because they are known or unknown.. I'd say, I rather don't like it.

> Have a look at [da00a95](https://github.com/tpope/vim-dadbod/commit/da00a957ac5d151896d0f9d0abcecf9e50c6037e) and see if that looks reasonable to you.

Unfortunetely, https://github.com/tpope/vim-dadbod/commit/da00a957ac5d151896d0f9d0abcecf9e50c6037e#diff-206372fc5a380a2736d4903f9a3b4fc4c80c517d481946a0af6a9812c7acab57R22 looks very wrong to me. The most of `clickhouse-client` arguments are [settings](https://clickhouse.tech/docs/en/operations/settings/settings/) accepting strings. It can be almost anything including empty string [1](https://clickhouse.tech/docs/en/operations/settings/settings/#settings-log-comment), [2](https://clickhouse.tech/docs/en/operations/settings/settings/#format_avro_schema_registry_url), [3](https://clickhouse.tech/docs/en/operations/settings/settings/#settings-join_default_strictness). And checking it for 1 at the beginning (and even the whole value) won't work as expected.

I honestly don't know which way would it be more correct, than using the same semantic as the client binary..

I just checked how the go `http.Request` behaves with and without `=`:

```
vals: net/url.Values [
        "with-equal": [""],
        "without-equal": [""],
]
r.RequestURI: "/render/?with-equal=&without-equal"
```

You are right, by standard they are the same. But I don't know how then distinguish the parameter w/o the following argument. =\

**Comment by tpope** [comment]
> Unfortunetely, [da00a95#diff-206372fc5a380a2736d4903f9a3b4fc4c80c517d481946a0af6a9812c7acab57R22](https://github.com/tpope/vim-dadbod/commit/da00a957ac5d151896d0f9d0abcecf9e50c6037e#diff-206372fc5a380a2736d4903f9a3b4fc4c80c517d481946a0af6a9812c7acab57R22) looks very wrong to me. The most of `clickhouse-client` arguments are [settings](https://clickhouse.tech/docs/en/operations/settings/settings/) accepting strings. It can be almost anything including empty string [1](https://clickhouse.tech/docs/en/operations/settings/settings/#settings-log-comment), [2](https://clickhouse.tech/docs/en/operations/settings/settings/#format_avro_schema_registry_url), [3](https://clickhouse.tech/docs/en/operations/settings/settings/#settings-join_default_strictness). And checking it for 1 at the beginning (and even the whole value) won't work as expected. `true` is a valid parameter for [input-format-parallel-parsing](https://clickhouse.tech/docs/en/operations/settings/settings/#input-format-parallel-parsing), for example.

Take a closer look at the first half of the conditional. If the key _isn't_ one of the 5 special cases, and value _isn't_ the `1` produced by `?param` with no `=`, this `elseif` is never reached. Here's a version that might be a bit clearer, at the expense of repetition:

```vim
    if k =~# '^\%(multiline\|multiquery\|time\|stacktrace\|secure\)$'
      if v =~# '^[1Tt]'
        call add(cmd, '--' . k)
      endif
    else
      if v is# 1
        call add(cmd, '--' . k)
      else
        call add(cmd, '--' . k . '=' . v)
      endif
    endif
```

> > This `?param` syntax is nonstandard and kind of weird, which is why I left it undocumented. I think supporting `?arbitrary-flag` is a reasonable behavior, but for known flags, `?secure=true` should remain the official, documented behavior.
> 
> Hmm, it looks inconsistent to me. Lately, `clickhouse-client` interface may change in any way, and have arguments that behave differently because they are known or unknown.. I'd say, I rather don't like it.

Honestly the crux of the issue here is that we are accepting unknown query parameters at all. The only adapters that do this are user contributions I decided not to be a hard-ass about. I'd support limiting to a known set.

> I just checked how the go `http.Request` behaves with and without `=`:
> 
> ```
> vals: net/url.Values [
>         "with-equal": [""],
>         "without-equal": [""],
> ]
> r.RequestURI: "/render/?with-equal=&without-equal"
> ```
> 
> You are right, by standard they are the same. But I don't know how then distinguish the parameter w/o the following argument. =\

It's worse than that. There is no standard. Here's what Ruby does:

```
>> CGI.parse('with-equal=&without-equal')
=> {"with-equal"=>[""], "without-equal"=>[]}
```

So my compromise is to _accept_ `?without-equal`, but not to encourage it or rely on it.

**Comment by Felixoid** [comment]
Good morning Tim. After taking the topic for a night, I have a clearer understanding of your point

> Here's a version that might be a bit clearer, at the expense of repetition

This version will work, indeed. The condition in [patch](https://github.com/tpope/vim-dadbod/commit/da00a957ac5d151896d0f9d0abcecf9e50c6037e#diff-206372fc5a380a2736d4903f9a3b4fc4c80c517d481946a0af6a9812c7acab57R20-R24) won't, because it doesn't have the branch that will set the parameter, for example, `--ask-password`. Sorry for the unclear statement, it was my point. Thank you for fixing it.

> I'd support limiting to a known set.

I understand the point. Although, CH is a very actively developing project and changes very intensively. So thank you very much for accepting the workaround!

My last question is then: should it stay a hidden functional then and not be reflected in the documentation?

**Comment by Felixoid** [comment]
> The two conditionals should produce identical results. If you disagree, please provide a counterexample in the form of a complete URL.

You are right. I didn't expect `int 1` to match the regexp. It's something new I've learned today, thank you.

I'll really appreciate, if you'd merge your branch into master.

**Comment by tpope** [comment]
It's merged.

**Pull request closed without merging**
