### PR TITLE
Issue #21 Parse ssl parameter from url and append authentication flags

### PR DESCRIPTION
**Pull request by oolongtea**
Here are the results that worked in my testing
```
:echo db#adapter#dispatch("mongodb://user@mymongo.com:9011/mydb?ssl=true", "interactive")
```
```
mongo --host 'mymongo.com' --port '9011' -u 'user' -p 'password'  --authenticationDatabase 'mydb' --ssl mydb
```

Let me know what you think. Thanks

### CODE REVIEW

**Comment by tpope** [comment]
You've got the right idea.

* You can pass `url` rather than `a:url` to `db#url#as_args()` to save an extra parse.
* Not clear what you were going for with `--authenticationDatabase` but I think you should drop it along with the extra database name append at the bottom.
* Let's be liberal in what we accept and use `if get(url.params, 'ssl') =~# '^[1t]'` to also allow `?ssl=1`.
* [Fix your commit message](https://commit.style).

**Comment by oolongtea** [comment]
Thanks for the feedback. I'll update these things. 

I only had an issue when I tried to pass `url` directly and got this error:
```
E121: Undefined variable: url
E116: Invalid arguments for function db#url#parse
E15: Invalid expression: db#url#parse(url)
```

I'll investigate why this is happening here.

**Comment by tpope** [comment]
Change the `#as_args` call, not the `#parse` call.

**Comment by tpope** [comment]
Sorry to yank this out from under you, but I really want to get it into the next release.

**Pull request closed without merging**
